function SetError(id, err) {
    const element = document.getElementById(id);
    element.getElementsByClassName("formerror")[0].innerHTML = err;
}

function clearErrors() {
    const errors = document.getElementsByClassName("formerror");
    for (let e of errors) {
        e.innerHTML = "";
    }

}
const form = document.querySelector('form');

form.addEventListener('submit', function (e) {
    e.preventDefault();

    clearErrors();

    const name = document.getElementById("name").value;
    const email = document.getElementById("email").value;
    const phone = document.getElementById("phoneNumber").value;
    const pswd = document.getElementById("pswd").value;
    const cnfrpswd = document.getElementById("cnfr").value;

    if (name.length >= 10) {
        SetError("div1", "*name should not greater than length of 10");
    }
    if (email.length > 20) {
        SetError("div2", "*email should not greater than length of 20");
    }
    if (phone.length != 10) {
        SetError("div3", "*Phone Number should not be less than or greater than length of 10");
    }
    if (pswd.length > 6) {
        SetError("div4", "*password should not be greater than 6")
    }
    if (cnfrpswd.length != pswd.length) {
        SetError("div5", "*please enter same password as password field...")
    }
    window.location = "mailto:test@example.com?subject=" + "Auto-generated email"  + "&body=" + `This is an auto-generated email generated by this email: ${email}`;
})